### PR TITLE
ignore archived repositories

### LINKED ISSUE #26: Seal reports on PRs on archived repositories
The seal notifies people about open PRs on archived repositories.  This is problematic because it's impossible to close or merge a PR on an archived repository without un-archiving it first.

### PR DESCRIPTION
**Pull request by philandstuff**
You can't do anything with PRs in archived repos (without unarchiving
them first), and you probably don't want to.

Fixes #26.

### CODE REVIEW

**Comment by philandstuff** [comment]
I tested this manually locally, but I didn't work too hard thinking about how I could have written a spec for it.

**Review by kevindew — APPROVED** [review]

**Comment by philandstuff** [comment]
Thanks for the review. What's the process now? I can't merge because it's still awaiting a jenkins report which I'm guessing isn't coming.

**Comment by issyl0** [comment]
I attempted to write a test for this so that CI would work on this branch but I'm not awake enough. 😞

Force-pushing the changes to `origin` doesn't work as "everything up-to-date" because this branch is already on `origin`.

**Comment by issyl0** [comment]
Scratch that. I was just over complicating things at 0830 in the morning. My commit makes the test stubs for searching issues have the same `archived: false` as the code.

**Comment by philandstuff** [comment]
Thanks very much, @issyl0!

I see the build is marked as failed, but trawling through the jenkins output doesn't show anything more meaningful (to me) than:

> `[build] 38 examples, 0 failures`

I tried to understand what the build is actually doing, but I don't understand Jenkinsfile and I don't know what its call to `govuk.buildProject()` is invoking.  If I follow the README instructions and just run `rspec`, I don't see any failures.

¯\_(ツ)_/¯

**Pull request merged**
