### PR TITLE
Add compact option

### PR DESCRIPTION
**Pull request by elliotcm**
Removes approved PRs from lists of fresh PRs and adds a `compact: true` / `COMPACT=true` config option which provides more compact PR output.

Before:
screenshot 2018-07-27 11 08 57

After:
screenshot 2018-07-27 11 10 02

https://trello.com/c/JA6NvD5o/335-refactor-and-restyle-slack-seal-output

### CODE REVIEW

**Review by binaryberry — APPROVED** [review]
Looks good! Just so I understand: this filters out approved PRs for all teams, and displays the compact version of the message for teams that have `compact` set as true?

(The message_builder_spec seems to suggest this as compact is set to false but the test expects approved PRs to have been filtered out)

**Review by thomasleese — APPROVED** [review]
Looks fine, but I wonder if it would be better to leave the approved PRs but have them in their own section like "PRs that can be merged today". This way it keeps them out of the way of PRs that need reviewing, but it also means we won't forget about them and still encourages something to be done with them.

**Comment by elliotcm** [comment]
@thomasleese Sounds good.  Let's leave that for a followup, the way the message builder segments PRs for different templates could use some work anyway.

**Comment by elliotcm** [comment]
We can also look at this issue from @philandstuff when we do that.

https://github.com/alphagov/seal/issues/26

**Pull request merged**
